### ISSUE TITLE
Add windows support.

### ISSUE THREAD

**Issue by codebymikey** [javierbrea/node-sass-alias-importer#22]
**Describe the bug**

The https://github.com/javierbrea/node-sass-alias-importer/commit/9486588dfabc75bc47f3ee9c99bbf36dc2095ea1 commit attempts to add path support presumably to support Windows environments.

However this leads to aliases no longer working because most scss imports use `@import "foo/bar";` rather than `@import "foo\\bar";` which is what the code would be checking on Windows.

The fix for that is this:
```diff
--- if (!aliasFound && url.split(path.sep)[0] === aliasDetails.alias) {
+++ if (!aliasFound && url.split('/')[0] === aliasDetails.alias) {
```

**To Reproduce**
Run a test on a windows environment.

**Expected behavior**
The alias is updated.

**Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS: Windows 10
 - Node.js: v12.2.0
 - npm: 6.9.0

**Comment by javierbrea** [comment]
Hi @codebymikey, thanks for your help and sorry for the delay!
I will add tests execution also on Windows OS in the build pipeline and publish a fix as soon as possible.
