### ISSUE TITLE
Bump node version to 16 / 17

### ISSUE THREAD

**Issue by theprometeus** [javierbrea/node-sass-alias-importer#36]
Node LTS at the time I'm writing this issue is 16.13.0
The currently supported node versions are 10, 11, 12, 14 and 15, but the module works fine with Node 16.

**Comment by javierbrea** [comment]
Released in [v1.1.0](https://github.com/javierbrea/node-sass-alias-importer/releases/tag/v1.1.0)

**Comment by theprometeus** [comment]
Same issue, happening again.

```
error node-sass-alias-importer@1.0.1: The engine "node" is incompatible with this module. Expected version "10.x || 12.x || 14.x || 15.x". Got "16.15.1"
```

I really think that it should support any node version by default since it's not a node version-specific module that can break with node updates.

It is an overkill to specify all versions that the module support since it support any node version by default :/

**Comment by javierbrea** [comment]
Hi @theprometeus ,
It supports any NodeJs version equal or greater than 10 from version 1.1.0. In fact, the CI pipeline uses NodeJs 16.

It seems that you are trying to use the version 1.0.1. You should update your dependency to the latest version.
