### ISSUE TITLE
"Error: done is not a function" in sync render sass mode

### ISSUE THREAD

**Issue by yarkeev** [javierbrea/node-sass-alias-importer#37]
In node-sass synchronous render mode, the done callback is not passed to the importer handler.
It is expected that the result will simply be returned from the handler.

Async mode: https://github.com/sass/node-sass/blob/master/lib/index.js#L324
Sync mode https://github.com/sass/node-sass/blob/master/lib/index.js#L403

**Comment by javierbrea** [comment]
Released in [v1.1.0](https://github.com/javierbrea/node-sass-alias-importer/releases/tag/v1.1.0)
